version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Persistent data
  rails_backend:
    image: rails.backend:0.0.1
    build: .
    command: bash -c "./start_rails_and_jobs_worker.sh"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - "1234:1234" # RubyMine Debug port
    depends_on:
      - db